---
- name: mastodon
  hosts: mastodon
  remote_user: root
  roles:
    - init
    - security
    - docker
    - mastodon
    - nginx
    - postfix
    - certbot
  vars:
    postfix:
      destination_domains:
        - noisebridge.social
