---
 - name: install fail2ban, git, sudo
   with_items:
     - fail2ban
     - git
     - sudo
   apt: package="{{ item }}" state=latest update_cache=yes cache_valid_time=3600
   tags:
     - apt
     - security
